services:

  database:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    volumes:
      - database-dev-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=database-dev

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    volumes:
      - redis-dev-data:/data
    ports:
      - '6379:6379'

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-dev-data:/data
    command: server /data --console-address ":9001"

volumes:
  database-dev-data:
  redis-dev-data:
  minio-dev-data: