spring:

  profiles:
    default: dev

  datasource:
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
      resolve-lazily: true
  sql:
    init:
      mode: always
