spring:

  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: redis
      port: 6379
#      password: ${REDIS_PASSWORD}
      database: 0

minio:
  url: http://minio:9000
  username: ${MINIO_USER}
  password: ${MINIO_PASSWORD}
  bucket: ${MINIO_BUCKET}

security:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}